const works = [
    { name: "Adam Marshall", image: "uploads/Adam_Marshall.png", code: "code/Adam_Marshall.js" },
    { name: "Angelo Castillo", image: "uploads/Angelo_Castillo.png", code: "code/Angelo_Castillo.js" },
    { name: "Bolong Sun", image: "uploads/Bolong_Sun.png", code: "code/Bolong_Sun.js" },
    { name: "Brady Anderson", image: "uploads/Brady_Anderson.png", code: "code/Brady_Anderson.js" },
    { name: "Cam McCullagh", image: "uploads/Cam_McCullagh.png", code: "code/Cam_McCullagh.js" },
    { name: "Connor Stewart", image: "uploads/Connor_Stewart.png", code: "code/Connor_Stewart.js" },
    { name: "Darren Dong", image: "uploads/Darren_Dong.png", code: "code/Darren_Dong.js" },
    { name: "Deron Nwangboje", image: "uploads/Deron_Nwangboje.png", code: "code/Deron_Nwangboje.js" },
    { name: "Dinneya", image: "uploads/Dinneya.png", code: "code/Dinneya.js" },
    { name: "Ebrar Ejder", image: "uploads/Ebrar_Ejder.png", code: "code/Ebrar_Ejder.js" },
    { name: "Ella Kalnins", image: "uploads/Ella_Kalnins.png", code: "code/Ella_Kalnins.js" },
    { name: "Emmanuel Atakora", image: "uploads/Emmanuel_Atakora.png", code: "code/Emmanuel_Atakora.js" },
    { name: "Emmitt Filkohazy", image: "uploads/Emmitt_Filkohazy.png", code: "code/Emmitt_Filkohazy.js" },
    { name: "Erfan Xu", image: "uploads/Erfan_Xu.png", code: "code/Erfan_Xu.js" },
    { name: "Gabriela Smith Forzzani", image: "uploads/Gabriela_Smith_Forzzani.png", code: "code/Gabriela_Smith_Forzzani.js" },
    { name: "Gwen Grandy", image: "uploads/Gwen_Grandy.png", code: "code/Gwen_Grandy.js" },
    { name: "Hanna Johnson", image: "uploads/Hanna_Johnson.png", code: "code/Hanna_Johnson.js" },
    { name: "Hayley Fehr", image: "uploads/Hayley_Fehr.png", code: "code/Hayley_Fehr.js" },
    { name: "Holly Karg", image: "uploads/Holly_Karg.png", code: "code/Holly_Karg.js" },
    { name: "Honour Tiemo", image: "uploads/Honour_Tiemo.png", code: "code/Honour_Tiemo.js" },
    { name: "Hunter Lobb", image: "uploads/Hunter_Lobb.png", code: "code/Hunter_Lobb.js" },
    { name: "Isabel Gramiak", image: "uploads/Isabel_Gramiak.png", code: "code/Isabel_Gramiak.js" },
    { name: "Jackson Smith", image: "uploads/Jackson_Smith.png", code: "code/Jackson_Smith.js" },
    { name: "Jaeden Hsu", image: "uploads/Jaeden_Hsu.png", code: "code/Jaeden_Hsu.js" },
    { name: "James Lamb", image: "uploads/James_Lamb.png", code: "code/James_Lamb.js" },
    { name: "Joe Haig", image: "uploads/Joe_Haig.png", code: "code/Joe_Haig.js" },
    { name: "John Hoa", image: "uploads/John_Hoa.png", code: "code/John_Hoa.js" },
    { name: "Joshua Lee", image: "uploads/Joshua_Lee.png", code: "code/Joshua_Lee.js" },
    { name: "Jun He", image: "uploads/Jun_He.png", code: "code/Jun_He.js" },
    { name: "Keegan Govender", image: "uploads/Keegan_Govender.png", code: "code/Keegan_Govender.js" },
    { name: "Kenny Ifeonu", image: "uploads/Kenny_Ifeonu.png", code: "code/Kenny_Ifeonu.js" },
    { name: "Kenny MacGregor", image: "uploads/Kenny_MacGregor.png", code: "code/Kenny_MacGregor.js" },
    { name: "Kiara Bott", image: "uploads/Kiara_Bott.png", code: "code/Kiara_Bott.js" },
    { name: "Kuzyk", image: "uploads/Kuzyk.png", code: "code/Kuzyk.js" },
    { name: "Kyle Irwin", image: "uploads/Kyle_Irwin.png", code: "code/Kyle_Irwin.js" },
    { name: "Lauren Whitling", image: "uploads/Lauren_Whitling.png", code: "code/Lauren_Whitling.js" },
    { name: "Lexi Eaton", image: "uploads/Lexi_Eaton.png", code: "code/Lexi_Eaton.js" },
    { name: "Logan Abel", image: "uploads/Logan_Abel.png", code: "code/Logan_Abel.js" },
    { name: "Luis Sandoval Ortiz", image: "uploads/Luis_Sandoval_Ortiz.png", code: "code/Luis_Sandoval_Ortiz.js" },
    { name: "Matt Friesen", image: "uploads/Matt_Friesen.png", code: "code/Matt_Friesen.js" },
    { name: "Melissa Bennett", image: "uploads/Melissa_Bennett.png", code: "code/Melissa_Bennett.js" },
    { name: "Min Kim", image: "uploads/Min_Kim.png", code: "code/Min_Kim.js" },
    { name: "Nathan Chan", image: "uploads/Nathan_Chan.png", code: "code/Nathan_Chan.js" },
    { name: "Nathan LeRoy", image: "uploads/Nathan_LeRoy.png", code: "code/Nathan_LeRoy.js" },
    { name: "Nik Doonanco", image: "uploads/Nik_Doonanco.png", code: "code/Nik_Doonanco.js" },
    { name: "Nnenna Nwankwo", image: "uploads/Nnenna_Nwankwo.png", code: "code/Nnenna_Nwankwo.js" },
    { name: "Owen Annear", image: "uploads/Owen_Annear.png", code: "code/Owen_Annear.js" },
    { name: "Quazi Farhat Islam", image: "uploads/Quazi_Farhat_Islam.png", code: "code/Quazi_Farhat_Islam.js" },
    { name: "Raine Moses", image: "uploads/Raine_Moses.png", code: "code/Raine_Moses.js" },
    { name: "Ria Purewal", image: "uploads/Ria_Purewal.png", code: "code/Ria_Purewal.js" },
    { name: "Russell Aquino", image: "uploads/Russell_Aquino.png", code: "code/Russell_Aquino.js" },
    { name: "Sarah Cossins", image: "uploads/Sarah_Cossins.png", code: "code/Sarah_Cossins.js" },
    { name: "Sara Sabir", image: "uploads/Sara_Sabir.png", code: "code/Sara_Sabir.js" },
    { name: "Sean Murray", image: "uploads/Sean_Murray.png", code: "code/Sean_Murray.js" },
    { name: "Sergio Ara Del Olmo", image: "uploads/Sergio_Ara_Del_Olmo.png", code: "code/Sergio_Ara_Del_Olmo.js" },
    { name: "Sergio Santillan Rivera", image: "uploads/Sergio_Santillan_Rivera.png", code: "code/Sergio_Santillan_Rivera.js" },
    { name: "Shea Dougan", image: "uploads/Shea_Dougan.png", code: "code/Shea_Dougan.js" },
    { name: "Shea Lane", image: "uploads/Shea_Lane.png", code: "code/Shea_Lane.js" },
    { name: "Stephen Zheng", image: "uploads/Stephen_Zheng.png", code: "code/Stephen_Zheng.js" },
    { name: "Subhagya Adhikari", image: "uploads/Subhagya_Adhikari.png", code: "code/Subhagya_Adhikari.js" },
    { name: "Ty Crozier", image: "uploads/Ty_Crozier.png", code: "code/Ty_Crozier.js" },
    { name: "Vasudev Jayadev", image: "uploads/Vasudev_Jayadev.png", code: "code/Vasudev_Jayadev.js" },
    { name: "William Leach", image: "uploads/William_Leach.png", code: "code/William_Leach.js" },
    { name: "Wilson Junior Voufo Awoubeng", image: "uploads/Wilson_Junior_Voufo_Awoubeng.png", code: "code/Wilson_Junior_Voufo_Awoubeng.js" },
    { name: "Xander Johnston", image: "uploads/Xander_Johnston.png", code: "code/Xander_Johnston.js" },
];
